<?php

use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
            array('name' => 'Afghanistan', 'iso_code_2' => 'AF', 'iso_code_3' => 'AFG'),
            array('name' => 'Albania', 'iso_code_2' => 'AL', 'iso_code_3' => 'ALB'),
            array('name' => 'Algeria', 'iso_code_2' => 'DZ', 'iso_code_3' => 'DZA'),
            array('name' => 'American Samoa', 'iso_code_2' => 'AS', 'iso_code_3' => 'ASM'),
            array('name' => 'Andorra', 'iso_code_2' => 'AD', 'iso_code_3' => 'AND'),
            array('name' => 'Angola', 'iso_code_2' => 'AO', 'iso_code_3' => 'AGO'),
            array('name' => 'Anguilla', 'iso_code_2' => 'AI', 'iso_code_3' => 'AIA'),
            array('name' => 'Antarctica', 'iso_code_2' => 'AQ', 'iso_code_3' => 'ATA'),
            array('name' => 'Antigua and Barbuda', 'iso_code_2' => 'AG', 'iso_code_3' => 'ATG'),
            array('name' => 'Argentina', 'iso_code_2' => 'AR', 'iso_code_3' => 'ARG'),
            array('name' => 'Armenia', 'iso_code_2' => 'AM', 'iso_code_3' => 'ARM'),
            array('name' => 'Aruba', 'iso_code_2' => 'AW', 'iso_code_3' => 'ABW'),
            array('name' => 'Australia', 'iso_code_2' => 'AU', 'iso_code_3' => 'AUS'),
            array('name' => 'Austria', 'iso_code_2' => 'AT', 'iso_code_3' => 'AUT'),
            array('name' => 'Azerbaijan', 'iso_code_2' => 'AZ', 'iso_code_3' => 'AZE'),
            array('name' => 'Bahamas', 'iso_code_2' => 'BS', 'iso_code_3' => 'BHS'),
            array('name' => 'Bahrain', 'iso_code_2' => 'BH', 'iso_code_3' => 'BHR'),
            array('name' => 'Bangladesh', 'iso_code_2' => 'BD', 'iso_code_3' => 'BGD'),
            array('name' => 'Barbados', 'iso_code_2' => 'BB', 'iso_code_3' => 'BRB'),
            array('name' => 'Belarus', 'iso_code_2' => 'BY', 'iso_code_3' => 'BLR'),
            array('name' => 'Belgium', 'iso_code_2' => 'BE', 'iso_code_3' => 'BEL'),
            array('name' => 'Belize', 'iso_code_2' => 'BZ', 'iso_code_3' => 'BLZ'),
            array('name' => 'Benin', 'iso_code_2' => 'BJ', 'iso_code_3' => 'BEN'),
            array('name' => 'Bermuda', 'iso_code_2' => 'BM', 'iso_code_3' => 'BMU'),
            array('name' => 'Bhutan', 'iso_code_2' => 'BT', 'iso_code_3' => 'BTN'),
            array('name' => 'Bolivia', 'iso_code_2' => 'BO', 'iso_code_3' => 'BOL'),
            array('name' => 'Bosnia and Herzegovina', 'iso_code_2' => 'BA', 'iso_code_3' => 'BIH'),
            array('name' => 'Botswana', 'iso_code_2' => 'BW', 'iso_code_3' => 'BWA'),
            array('name' => 'Bouvet Island', 'iso_code_2' => 'BV', 'iso_code_3' => 'BVT'),
            array('name' => 'Brasil', 'iso_code_2' => 'BR', 'iso_code_3' => 'BRA'),
            array('name' => 'British Indian Ocean Territory', 'iso_code_2' => 'IO', 'iso_code_3' => 'IOT'),
            array('name' => 'Brunei Darussalam', 'iso_code_2' => 'BN', 'iso_code_3' => 'BRN'),
            array('name' => 'Bulgaria', 'iso_code_2' => 'BG', 'iso_code_3' => 'BGR'),
            array('name' => 'Burkina Faso', 'iso_code_2' => 'BF', 'iso_code_3' => 'BFA'),
            array('name' => 'Burundi', 'iso_code_2' => 'BI', 'iso_code_3' => 'BDI'),
            array('name' => 'Cambodia', 'iso_code_2' => 'KH', 'iso_code_3' => 'KHM'),
            array('name' => 'Cameroon', 'iso_code_2' => 'CM', 'iso_code_3' => 'CMR'),
            array('name' => 'Canada', 'iso_code_2' => 'CA', 'iso_code_3' => 'CAN'),
            array('name' => 'Cape Verde', 'iso_code_2' => 'CV', 'iso_code_3' => 'CPV'),
            array('name' => 'Cayman Islands', 'iso_code_2' => 'KY', 'iso_code_3' => 'CYM'),
            array('name' => 'Central African Republic', 'iso_code_2' => 'CF', 'iso_code_3' => 'CAF'),
            array('name' => 'Chad', 'iso_code_2' => 'TD', 'iso_code_3' => 'TCD'),
            array('name' => 'Chile', 'iso_code_2' => 'CL', 'iso_code_3' => 'CHL'),
            array('name' => 'China', 'iso_code_2' => 'CN', 'iso_code_3' => 'CHN'),
            array('name' => 'Christmas Island', 'iso_code_2' => 'CX', 'iso_code_3' => 'CXR'),
            array('name' => 'Cocos (Keeling) Islands', 'iso_code_2' => 'CC', 'iso_code_3' => 'CCK'),
            array('name' => 'Colombia', 'iso_code_2' => 'CO', 'iso_code_3' => 'COL'),
            array('name' => 'Comoros', 'iso_code_2' => 'KM', 'iso_code_3' => 'COM'),
            array('name' => 'Congo', 'iso_code_2' => 'CG', 'iso_code_3' => 'COG'),
            array('name' => 'Cook Islands', 'iso_code_2' => 'CK', 'iso_code_3' => 'COK'),
            array('name' => 'Costa Rica', 'iso_code_2' => 'CR', 'iso_code_3' => 'CRI'),
            array('name' => 'Cote D\'Ivoire', 'iso_code_2' => 'CI', 'iso_code_3' => 'CIV'),
            array('name' => 'Croatia', 'iso_code_2' => 'HR', 'iso_code_3' => 'HRV'),
            array('name' => 'Cuba', 'iso_code_2' => 'CU', 'iso_code_3' => 'CUB'),
            array('name' => 'Cyprus', 'iso_code_2' => 'CY', 'iso_code_3' => 'CYP'),
            array('name' => 'Czech Republic', 'iso_code_2' => 'CZ', 'iso_code_3' => 'CZE'),
            array('name' => 'Denmark', 'iso_code_2' => 'DK', 'iso_code_3' => 'DNK'),
            array('name' => 'Djibouti', 'iso_code_2' => 'DJ', 'iso_code_3' => 'DJI'),
            array('name' => 'Dominica', 'iso_code_2' => 'DM', 'iso_code_3' => 'DMA'),
            array('name' => 'Dominican Republic', 'iso_code_2' => 'DO', 'iso_code_3' => 'DOM'),
            array('name' => 'East Timor', 'iso_code_2' => 'TL', 'iso_code_3' => 'TLS'),
            array('name' => 'Ecuador', 'iso_code_2' => 'EC', 'iso_code_3' => 'ECU'),
            array('name' => 'Egypt', 'iso_code_2' => 'EG', 'iso_code_3' => 'EGY'),
            array('name' => 'El Salvador', 'iso_code_2' => 'SV', 'iso_code_3' => 'SLV'),
            array('name' => 'Equatorial Guinea', 'iso_code_2' => 'GQ', 'iso_code_3' => 'GNQ'),
            array('name' => 'Eritrea', 'iso_code_2' => 'ER', 'iso_code_3' => 'ERI'),
            array('name' => 'Estonia', 'iso_code_2' => 'EE', 'iso_code_3' => 'EST'),
            array('name' => 'Ethiopia', 'iso_code_2' => 'ET', 'iso_code_3' => 'ETH'),
            array('name' => 'Falkland Islands (Malvinas)', 'iso_code_2' => 'FK', 'iso_code_3' => 'FLK'),
            array('name' => 'Faroe Islands', 'iso_code_2' => 'FO', 'iso_code_3' => 'FRO'),
            array('name' => 'Fiji', 'iso_code_2' => 'FJ', 'iso_code_3' => 'FJI'),
            array('name' => 'Finland', 'iso_code_2' => 'FI', 'iso_code_3' => 'FIN'),
            array('name' => 'France, Metropolitan', 'iso_code_2' => 'FR', 'iso_code_3' => 'FRA'),
            array('name' => 'French Guiana', 'iso_code_2' => 'GF', 'iso_code_3' => 'GUF'),
            array('name' => 'French Polynesia', 'iso_code_2' => 'PF', 'iso_code_3' => 'PYF'),
            array('name' => 'French Southern Territories', 'iso_code_2' => 'TF', 'iso_code_3' => 'ATF'),
            array('name' => 'Gabon', 'iso_code_2' => 'GA', 'iso_code_3' => 'GAB'),
            array('name' => 'Gambia', 'iso_code_2' => 'GM', 'iso_code_3' => 'GMB'),
            array('name' => 'Georgia', 'iso_code_2' => 'GE', 'iso_code_3' => 'GEO'),
            array('name' => 'Germany', 'iso_code_2' => 'DE', 'iso_code_3' => 'DEU'),
            array('name' => 'Ghana', 'iso_code_2' => 'GH', 'iso_code_3' => 'GHA'),
            array('name' => 'Gibraltar', 'iso_code_2' => 'GI', 'iso_code_3' => 'GIB'),
            array('name' => 'Greece', 'iso_code_2' => 'GR', 'iso_code_3' => 'GRC'),
            array('name' => 'Greenland', 'iso_code_2' => 'GL', 'iso_code_3' => 'GRL'),
            array('name' => 'Grenada', 'iso_code_2' => 'GD', 'iso_code_3' => 'GRD'),
            array('name' => 'Guadeloupe', 'iso_code_2' => 'GP', 'iso_code_3' => 'GLP'),
            array('name' => 'Guam', 'iso_code_2' => 'GU', 'iso_code_3' => 'GUM'),
            array('name' => 'Guatemala', 'iso_code_2' => 'GT', 'iso_code_3' => 'GTM'),
            array('name' => 'Guinea', 'iso_code_2' => 'GN', 'iso_code_3' => 'GIN'),
            array('name' => 'Guinea-Bissau', 'iso_code_2' => 'GW', 'iso_code_3' => 'GNB'),
            array('name' => 'Guyana', 'iso_code_2' => 'GY', 'iso_code_3' => 'GUY'),
            array('name' => 'Haiti', 'iso_code_2' => 'HT', 'iso_code_3' => 'HTI'),
            array('name' => 'Heard and Mc Donald Islands', 'iso_code_2' => 'HM', 'iso_code_3' => 'HMD'),
            array('name' => 'Honduras', 'iso_code_2' => 'HN', 'iso_code_3' => 'HND'),
            array('name' => 'Hong Kong', 'iso_code_2' => 'HK', 'iso_code_3' => 'HKG'),
            array('name' => 'Hungary', 'iso_code_2' => 'HU', 'iso_code_3' => 'HUN'),
            array('name' => 'Iceland', 'iso_code_2' => 'IS', 'iso_code_3' => 'ISL'),
            array('name' => 'India', 'iso_code_2' => 'IN', 'iso_code_3' => 'IND'),
            array('name' => 'Indonesia', 'iso_code_2' => 'ID', 'iso_code_3' => 'IDN'),
            array('name' => 'Iran (Islamic Republic of)', 'iso_code_2' => 'IR', 'iso_code_3' => 'IRN'),
            array('name' => 'Iraq', 'iso_code_2' => 'IQ', 'iso_code_3' => 'IRQ'),
            array('name' => 'Ireland', 'iso_code_2' => 'IE', 'iso_code_3' => 'IRL'),
            array('name' => 'Israel', 'iso_code_2' => 'IL', 'iso_code_3' => 'ISR'),
            array('name' => 'Italy', 'iso_code_2' => 'IT', 'iso_code_3' => 'ITA'),
            array('name' => 'Jamaica', 'iso_code_2' => 'JM', 'iso_code_3' => 'JAM'),
            array('name' => 'Japan', 'iso_code_2' => 'JP', 'iso_code_3' => 'JPN'),
            array('name' => 'Jordan', 'iso_code_2' => 'JO', 'iso_code_3' => 'JOR'),
            array('name' => 'Kazakhstan', 'iso_code_2' => 'KZ', 'iso_code_3' => 'KAZ'),
            array('name' => 'Kenya', 'iso_code_2' => 'KE', 'iso_code_3' => 'KEN'),
            array('name' => 'Kiribati', 'iso_code_2' => 'KI', 'iso_code_3' => 'KIR'),
            array('name' => 'North Korea', 'iso_code_2' => 'KP', 'iso_code_3' => 'PRK'),
            array('name' => 'South Korea', 'iso_code_2' => 'KR', 'iso_code_3' => 'KOR'),
            array('name' => 'Kuwait', 'iso_code_2' => 'KW', 'iso_code_3' => 'KWT'),
            array('name' => 'Kyrgyzstan', 'iso_code_2' => 'KG', 'iso_code_3' => 'KGZ'),
            array('name' => 'Lao People\'s Democratic Republic', 'iso_code_2' => 'LA', 'iso_code_3' => 'LAO'),
            array('name' => 'Latvia', 'iso_code_2' => 'LV', 'iso_code_3' => 'LVA'),
            array('name' => 'Lebanon', 'iso_code_2' => 'LB', 'iso_code_3' => 'LBN'),
            array('name' => 'Lesotho', 'iso_code_2' => 'LS', 'iso_code_3' => 'LSO'),
            array('name' => 'Liberia', 'iso_code_2' => 'LR', 'iso_code_3' => 'LBR'),
            array('name' => 'Libyan Arab Jamahiriya', 'iso_code_2' => 'LY', 'iso_code_3' => 'LBY'),
            array('name' => 'Liechtenstein', 'iso_code_2' => 'LI', 'iso_code_3' => 'LIE'),
            array('name' => 'Lithuania', 'iso_code_2' => 'LT', 'iso_code_3' => 'LTU'),
            array('name' => 'Luxembourg', 'iso_code_2' => 'LU', 'iso_code_3' => 'LUX'),
            array('name' => 'Macau', 'iso_code_2' => 'MO', 'iso_code_3' => 'MAC'),
            array('name' => 'FYROM', 'iso_code_2' => 'MK', 'iso_code_3' => 'MKD'),
            array('name' => 'Madagascar', 'iso_code_2' => 'MG', 'iso_code_3' => 'MDG'),
            array('name' => 'Malawi', 'iso_code_2' => 'MW', 'iso_code_3' => 'MWI'),
            array('name' => 'Malaysia', 'iso_code_2' => 'MY', 'iso_code_3' => 'MYS'),
            array('name' => 'Maldives', 'iso_code_2' => 'MV', 'iso_code_3' => 'MDV'),
            array('name' => 'Mali', 'iso_code_2' => 'ML', 'iso_code_3' => 'MLI'),
            array('name' => 'Malta', 'iso_code_2' => 'MT', 'iso_code_3' => 'MLT'),
            array('name' => 'Marshall Islands', 'iso_code_2' => 'MH', 'iso_code_3' => 'MHL'),
            array('name' => 'Martinique', 'iso_code_2' => 'MQ', 'iso_code_3' => 'MTQ'),
            array('name' => 'Mauritania', 'iso_code_2' => 'MR', 'iso_code_3' => 'MRT'),
            array('name' => 'Mauritius', 'iso_code_2' => 'MU', 'iso_code_3' => 'MUS'),
            array('name' => 'Mayotte', 'iso_code_2' => 'YT', 'iso_code_3' => 'MYT'),
            array('name' => 'Mexico', 'iso_code_2' => 'MX', 'iso_code_3' => 'MEX'),
            array('name' => 'Micronesia, Federated States of', 'iso_code_2' => 'FM', 'iso_code_3' => 'FSM'),
            array('name' => 'Moldova, Republic of', 'iso_code_2' => 'MD', 'iso_code_3' => 'MDA'),
            array('name' => 'Monaco', 'iso_code_2' => 'MC', 'iso_code_3' => 'MCO'),
            array('name' => 'Mongolia', 'iso_code_2' => 'MN', 'iso_code_3' => 'MNG'),
            array('name' => 'Montserrat', 'iso_code_2' => 'MS', 'iso_code_3' => 'MSR'),
            array('name' => 'Morocco', 'iso_code_2' => 'MA', 'iso_code_3' => 'MAR'),
            array('name' => 'Mozambique', 'iso_code_2' => 'MZ', 'iso_code_3' => 'MOZ'),
            array('name' => 'Myanmar', 'iso_code_2' => 'MM', 'iso_code_3' => 'MMR'),
            array('name' => 'Namibia', 'iso_code_2' => 'NA', 'iso_code_3' => 'NAM'),
            array('name' => 'Nauru', 'iso_code_2' => 'NR', 'iso_code_3' => 'NRU'),
            array('name' => 'Nepal', 'iso_code_2' => 'NP', 'iso_code_3' => 'NPL'),
            array('name' => 'Netherlands', 'iso_code_2' => 'NL', 'iso_code_3' => 'NLD'),
            array('name' => 'Netherlands Antilles', 'iso_code_2' => 'AN', 'iso_code_3' => 'ANT'),
            array('name' => 'New Caledonia', 'iso_code_2' => 'NC', 'iso_code_3' => 'NCL'),
            array('name' => 'New Zealand', 'iso_code_2' => 'NZ', 'iso_code_3' => 'NZL'),
            array('name' => 'Nicaragua', 'iso_code_2' => 'NI', 'iso_code_3' => 'NIC'),
            array('name' => 'Niger', 'iso_code_2' => 'NE', 'iso_code_3' => 'NER'),
            array('name' => 'Nigeria', 'iso_code_2' => 'NG', 'iso_code_3' => 'NGA'),
            array('name' => 'Niue', 'iso_code_2' => 'NU', 'iso_code_3' => 'NIU'),
            array('name' => 'Norfolk Island', 'iso_code_2' => 'NF', 'iso_code_3' => 'NFK'),
            array('name' => 'Northern Mariana Islands', 'iso_code_2' => 'MP', 'iso_code_3' => 'MNP'),
            array('name' => 'Norway', 'iso_code_2' => 'NO', 'iso_code_3' => 'NOR'),
            array('name' => 'Oman', 'iso_code_2' => 'OM', 'iso_code_3' => 'OMN'),
            array('name' => 'Pakistan', 'iso_code_2' => 'PK', 'iso_code_3' => 'PAK'),
            array('name' => 'Palau', 'iso_code_2' => 'PW', 'iso_code_3' => 'PLW'),
            array('name' => 'Panama', 'iso_code_2' => 'PA', 'iso_code_3' => 'PAN'),
            array('name' => 'Papua New Guinea', 'iso_code_2' => 'PG', 'iso_code_3' => 'PNG'),
            array('name' => 'Paraguay', 'iso_code_2' => 'PY', 'iso_code_3' => 'PRY'),
            array('name' => 'Peru', 'iso_code_2' => 'PE', 'iso_code_3' => 'PER'),
            array('name' => 'Philippines', 'iso_code_2' => 'PH', 'iso_code_3' => 'PHL'),
            array('name' => 'Pitcairn', 'iso_code_2' => 'PN', 'iso_code_3' => 'PCN'),
            array('name' => 'Poland', 'iso_code_2' => 'PL', 'iso_code_3' => 'POL'),
            array('name' => 'Portugal', 'iso_code_2' => 'PT', 'iso_code_3' => 'PRT'),
            array('name' => 'Puerto Rico', 'iso_code_2' => 'PR', 'iso_code_3' => 'PRI'),
            array('name' => 'Qatar', 'iso_code_2' => 'QA', 'iso_code_3' => 'QAT'),
            array('name' => 'Reunion', 'iso_code_2' => 'RE', 'iso_code_3' => 'REU'),
            array('name' => 'Romania', 'iso_code_2' => 'RO', 'iso_code_3' => 'ROM'),
            array('name' => 'Russian Federation', 'iso_code_2' => 'RU', 'iso_code_3' => 'RUS'),
            array('name' => 'Rwanda', 'iso_code_2' => 'RW', 'iso_code_3' => 'RWA'),
            array('name' => 'Saint Kitts and Nevis', 'iso_code_2' => 'KN', 'iso_code_3' => 'KNA'),
            array('name' => 'Saint Lucia', 'iso_code_2' => 'LC', 'iso_code_3' => 'LCA'),
            array('name' => 'Saint Vincent and the Grenadines', 'iso_code_2' => 'VC', 'iso_code_3' => 'VCT'),
            array('name' => 'Samoa', 'iso_code_2' => 'WS', 'iso_code_3' => 'WSM'),
            array('name' => 'San Marino', 'iso_code_2' => 'SM', 'iso_code_3' => 'SMR'),
            array('name' => 'Sao Tome and Principe', 'iso_code_2' => 'ST', 'iso_code_3' => 'STP'),
            array('name' => 'Saudi Arabia', 'iso_code_2' => 'SA', 'iso_code_3' => 'SAU'),
            array('name' => 'Senegal', 'iso_code_2' => 'SN', 'iso_code_3' => 'SEN'),
            array('name' => 'Seychelles', 'iso_code_2' => 'SC', 'iso_code_3' => 'SYC'),
            array('name' => 'Sierra Leone', 'iso_code_2' => 'SL', 'iso_code_3' => 'SLE'),
            array('name' => 'Singapore', 'iso_code_2' => 'SG', 'iso_code_3' => 'SGP'),
            array('name' => 'Slovak Republic', 'iso_code_2' => 'SK', 'iso_code_3' => 'SVK'),
            array('name' => 'Slovenia', 'iso_code_2' => 'SI', 'iso_code_3' => 'SVN'),
            array('name' => 'Solomon Islands', 'iso_code_2' => 'SB', 'iso_code_3' => 'SLB'),
            array('name' => 'Somalia', 'iso_code_2' => 'SO', 'iso_code_3' => 'SOM'),
            array('name' => 'South Africa', 'iso_code_2' => 'ZA', 'iso_code_3' => 'ZAF'),
            array('name' => 'South Georgia &amp; South Sandwich Islands', 'iso_code_2' => 'GS', 'iso_code_3' => 'SGS'),
            array('name' => 'Spain', 'iso_code_2' => 'ES', 'iso_code_3' => 'ESP'),
            array('name' => 'Sri Lanka', 'iso_code_2' => 'LK', 'iso_code_3' => 'LKA'),
            array('name' => 'St. Helena', 'iso_code_2' => 'SH', 'iso_code_3' => 'SHN'),
            array('name' => 'St. Pierre and Miquelon', 'iso_code_2' => 'PM', 'iso_code_3' => 'SPM'),
            array('name' => 'Sudan', 'iso_code_2' => 'SD', 'iso_code_3' => 'SDN'),
            array('name' => 'Suriname', 'iso_code_2' => 'SR', 'iso_code_3' => 'SUR'),
            array('name' => 'Svalbard and Jan Mayen Islands', 'iso_code_2' => 'SJ', 'iso_code_3' => 'SJM'),
            array('name' => 'Swaziland', 'iso_code_2' => 'SZ', 'iso_code_3' => 'SWZ'),
            array('name' => 'Sweden', 'iso_code_2' => 'SE', 'iso_code_3' => 'SWE'),
            array('name' => 'Switzerland', 'iso_code_2' => 'CH', 'iso_code_3' => 'CHE'),
            array('name' => 'Syrian Arab Republic', 'iso_code_2' => 'SY', 'iso_code_3' => 'SYR'),
            array('name' => 'Taiwan', 'iso_code_2' => 'TW', 'iso_code_3' => 'TWN'),
            array('name' => 'Tajikistan', 'iso_code_2' => 'TJ', 'iso_code_3' => 'TJK'),
            array('name' => 'Tanzania, United Republic of', 'iso_code_2' => 'TZ', 'iso_code_3' => 'TZA'),
            array('name' => 'Thailand', 'iso_code_2' => 'TH', 'iso_code_3' => 'THA'),
            array('name' => 'Togo', 'iso_code_2' => 'TG', 'iso_code_3' => 'TGO'),
            array('name' => 'Tokelau', 'iso_code_2' => 'TK', 'iso_code_3' => 'TKL'),
            array('name' => 'Tonga', 'iso_code_2' => 'TO', 'iso_code_3' => 'TON'),
            array('name' => 'Trinidad and Tobago', 'iso_code_2' => 'TT', 'iso_code_3' => 'TTO'),
            array('name' => 'Tunisia', 'iso_code_2' => 'TN', 'iso_code_3' => 'TUN'),
            array('name' => 'Turkey', 'iso_code_2' => 'TR', 'iso_code_3' => 'TUR'),
            array('name' => 'Turkmenistan', 'iso_code_2' => 'TM', 'iso_code_3' => 'TKM'),
            array('name' => 'Turks and Caicos Islands', 'iso_code_2' => 'TC', 'iso_code_3' => 'TCA'),
            array('name' => 'Tuvalu', 'iso_code_2' => 'TV', 'iso_code_3' => 'TUV'),
            array('name' => 'Uganda', 'iso_code_2' => 'UG', 'iso_code_3' => 'UGA'),
            array('name' => 'Ukraine', 'iso_code_2' => 'UA', 'iso_code_3' => 'UKR'),
            array('name' => 'United Arab Emirates', 'iso_code_2' => 'AE', 'iso_code_3' => 'ARE'),
            array('name' => 'United Kingdom', 'iso_code_2' => 'GB', 'iso_code_3' => 'GBR'),
            array('name' => 'United States', 'iso_code_2' => 'US', 'iso_code_3' => 'USA'),
            array('name' => 'United States Minor Outlying Islands', 'iso_code_2' => 'UM', 'iso_code_3' => 'UMI'),
            array('name' => 'Uruguay', 'iso_code_2' => 'UY', 'iso_code_3' => 'URY'),
            array('name' => 'Uzbekistan', 'iso_code_2' => 'UZ', 'iso_code_3' => 'UZB'),
            array('name' => 'Vanuatu', 'iso_code_2' => 'VU', 'iso_code_3' => 'VUT'),
            array('name' => 'Vatican City State (Holy See)', 'iso_code_2' => 'VA', 'iso_code_3' => 'VAT'),
            array('name' => 'Venezuela', 'iso_code_2' => 'VE', 'iso_code_3' => 'VEN'),
            array('name' => 'Viet Nam', 'iso_code_2' => 'VN', 'iso_code_3' => 'VNM'),
            array('name' => 'Virgin Islands (British)', 'iso_code_2' => 'VG', 'iso_code_3' => 'VGB'),
            array('name' => 'Virgin Islands (U.S.)', 'iso_code_2' => 'VI', 'iso_code_3' => 'VIR'),
            array('name' => 'Wallis and Futuna Islands', 'iso_code_2' => 'WF', 'iso_code_3' => 'WLF'),
            array('name' => 'Western Sahara', 'iso_code_2' => 'EH', 'iso_code_3' => 'ESH'),
            array('name' => 'Yemen', 'iso_code_2' => 'YE', 'iso_code_3' => 'YEM'),
            array('name' => 'Democratic Republic of Congo', 'iso_code_2' => 'CD', 'iso_code_3' => 'COD'),
            array('name' => 'Zambia', 'iso_code_2' => 'ZM', 'iso_code_3' => 'ZMB'),
            array('name' => 'Zimbabwe', 'iso_code_2' => 'ZW', 'iso_code_3' => 'ZWE'),
            array('name' => 'Montenegro', 'iso_code_2' => 'ME', 'iso_code_3' => 'MNE'),
            array('name' => 'Serbia', 'iso_code_2' => 'RS', 'iso_code_3' => 'SRB'),
            array('name' => 'Aaland Islands', 'iso_code_2' => 'AX', 'iso_code_3' => 'ALA'),
            array('name' => 'Bonaire, Sint Eustatius and Saba', 'iso_code_2' => 'BQ', 'iso_code_3' => 'BES'),
            array('name' => 'Curacao', 'iso_code_2' => 'CW', 'iso_code_3' => 'CUW'),
            array('name' => 'Palestinian Territory, Occupied', 'iso_code_2' => 'PS', 'iso_code_3' => 'PSE'),
            array('name' => 'South Sudan', 'iso_code_2' => 'SS', 'iso_code_3' => 'SSD'),
            array('name' => 'St. Barthelemy', 'iso_code_2' => 'BL', 'iso_code_3' => 'BLM'),
            array('name' => 'St. Martin (French part)', 'iso_code_2' => 'MF', 'iso_code_3' => 'MAF'),
            array('name' => 'Canary Islands', 'iso_code_2' => 'IC', 'iso_code_3' => 'ICA'),
            array('name' => 'Ascension Island (British)', 'iso_code_2' => 'AC', 'iso_code_3' => 'ASC'),
            array('name' => 'Kosovo, Republic of', 'iso_code_2' => 'XK', 'iso_code_3' => 'UNK'),
            array('name' => 'Isle of Man', 'iso_code_2' => 'IM', 'iso_code_3' => 'IMN'),
            array('name' => 'Tristan da Cunha', 'iso_code_2' => 'TA', 'iso_code_3' => 'SHN'),
            array('name' => 'Guernsey', 'iso_code_2' => 'GG', 'iso_code_3' => 'GGY'),
            array('name' => 'Jersey', 'iso_code_2' => 'JE', 'iso_code_3' => 'JEY')
        ]);
    }
}
